######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 29 15:36:45 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/m/c/mc163/Desktop/project/qt/. .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
